import Head from "next/head";
import Image from "next/image";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import Widget from "../components/Widget";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by Twitter Clone" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-black  min-h-screen max-w-[1300px] flex mx-auto">
        {/* Sidebar */}
        <Sidebar />

        {/* Feed */}
        <Feed />

        {/* Widget */}
        {/* <Widget /> */}

        {/* Modal */}
      </main>
    </div>
  );
}
